name: actions
on:
  push:
    branches:
      - '**'
jobs:
  debian-debootstrap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        QEMU_VER: [v7.2.0-1]
        DOCKER_REPO: [docker.io/multiarch/debian-debootstrap]
        VERSION: [bookworm]
        UNAME_ARCH: [x86_64, arm64, armel, armv7l, i386, mipsel, mips64el, ppc64el, s390x]
        include:
          - {ARCH: armhf,     QEMU_ARCH: arm,     UNAME_ARCH: armv7l}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu jammy main universe'
          sudo apt-get update && sudo apt-get install -y qemu-user-static debootstrap
          ./update.sh -a ${{ matrix.ARCH }} -v ${{ matrix.VERSION }} -q ${{ matrix.QEMU_ARCH }} -u ${{ matrix.QEMU_VER }} -d ${{ matrix.DOCKER_REPO }} -o ${{ matrix.UNAME_ARCH }}
      - name: Publish
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push -a ${{ matrix.DOCKER_REPO }}
